name: mern-booking-app

services:
  mern-booking-app-db:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
